<a href="https://colab.research.google.com/github/sanjay-MGR/Machine-Learning-basic-/blob/main/Ensemble_learnig_and_Boosting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##import laiberies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#load dataset
data = sns.load_dataset('tips')

In [ ]:
data.head(3)
df = data.copy()
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
data = data[['total_bill','tip','day']]

In [ ]:
#split data into x and y
x = data.drop('day',axis = 1)

In [ ]:
y = data.day

In [ ]:
#import train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [ ]:
#import model
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#build the model
base_model  = DecisionTreeClassifier()
base_model

DecisionTreeClassifier()

In [ ]:
#fit the model
base_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
#Boosting (AdaBoost)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
ada = AdaBoostClassifier(estimator=base_model,n_estimators=100,random_state=42)
#n_estimators=100 it retrain the model 100 times

In [ ]:
#fit the model
ada.fit(x_train,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(), n_estimators=100,
                   random_state=42)

In [ ]:
#perdic the value
y_pred = ada.predict(x_test)

In [ ]:
#check accuracy
from sklearn.metrics import accuracy_score

In [ ]:
acs = accuracy_score(y_test,y_pred)
acs #accuracy is 32% deu to data altered

0.32653061224489793

In [ ]:
#Regression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

In [ ]:
#load dataset
data = sns.load_dataset('mpg')

In [ ]:
data.head(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320

In [ ]:
data1 = data[['mpg','cylinders','displacement','horsepower']]

In [ ]:
X = data1.drop('mpg',axis = 1)
X.isna().sum()

cylinders       0
displacement    0
horsepower      6
dtype: int64

In [ ]:
X['horsepower'] = X['horsepower'].fillna(X['horsepower'].mean())

In [ ]:
X.isna().sum()

cylinders       0
displacement    0
horsepower      0
dtype: int64

In [ ]:
Y = data1.mpg

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42)

In [ ]:
#build the base model
base_modelR = DecisionTreeRegressor()
base_modelR

DecisionTreeRegressor()

In [ ]:
#fit the model
base_modelR.fit(X_train,Y_train)

DecisionTreeRegressor()

In [ ]:
#build model
adaR = AdaBoostRegressor(estimator=base_modelR,n_estimators=100,random_state=42)

In [ ]:
#trian model
adaR.fit(X_train,Y_train)

AdaBoostRegressor(estimator=DecisionTreeRegressor(), n_estimators=100,
                  random_state=42)

In [ ]:
#predict the value
Y_pred = adaR.predict(X_test)

In [ ]:
#check accuracy
from sklearn.metrics import r2_score
r2_score = r2_score(Y_test,Y_pred)
r2_score

0.6386316458891248

In [ ]:
# Gradient Boosting

In [ ]:
#FOR Classification
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
data_c = df[['total_bill','tip','size','sex']]

In [ ]:
a = data_c.drop('sex',axis = 1)
b = data_c.sex

In [ ]:
a_train,a_test,b_train,b_test = train_test_split(a,b,test_size = 0.2,random_state = 42)

In [ ]:
#base model
Gbase_model = DecisionTreeClassifier()
Gbase_model

DecisionTreeClassifier()

In [ ]:
#fit the model
Gbase_model.fit(a_train,b_train)

DecisionTreeClassifier()

In [ ]:
#predict the value
b_pred = Gbase_model.predict(a_test)

In [ ]:
#check accuracy
b_acs = accuracy_score(b_test,b_pred)
b_acs

0.5306122448979592

In [ ]:
#now use gardient boosting
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
#build the model
Gmodel_c = GradientBoostingClassifier(n_estimators=100,random_state=42)

In [ ]:
Gbase_model.fit(a_train,b_train)

DecisionTreeClassifier()

In [ ]:
#predic the b
b_predG = Gbase_model.predict(a_test)

In [ ]:
#check accuracy
b_acsG = accuracy_score(b_test,b_predG)
b_acsG

0.5306122448979592

In [ ]:
#FOR Regresor

In [ ]:
data_NG = data[['mpg','cylinders','displacement','horsepower']]

In [ ]:
#split data into x and y
A = data_NG.drop('mpg',axis = 1)
B = data_NG.mpg

In [ ]:
A.isna().sum()

cylinders       0
displacement    0
horsepower      6
dtype: int64

In [ ]:
A['horsepower'] = A['horsepower'].fillna(A['horsepower'].mean())

In [ ]:
A.isna().sum()

cylinders       0
displacement    0
horsepower      0
dtype: int64

In [ ]:
A_train,A_test,B_train,B_test = train_test_split(A,B,test_size = 0.2,random_state = 42)

In [ ]:
#build the model
base_modelRR = DecisionTreeRegressor()
base_modelRR

DecisionTreeRegressor()

In [ ]:
#fit the model
base_modelRR.fit(A_train,B_train)

DecisionTreeRegressor()

In [ ]:
#predict the value
B_pred = base_modelRR.predict(A_test)
B_pred

array([29.        , 27.4       , 18.6       , 14.88888889, 14.88888889,
       24.66666667, 25.        , 14.        , 20.        , 17.33333333,
       15.5       , 38.2       , 29.        , 15.66666667, 23.75      ,
       13.5       , 30.5       , 16.5       , 13.5       , 35.55      ,
       41.5       , 20.        , 20.13333333, 31.85      , 17.5       ,
       23.        , 24.        , 28.03333333, 15.5       , 14.5       ,
       22.        , 33.        , 15.5       , 24.        , 46.6       ,
       13.33333333, 19.        , 17.5       , 14.88888889, 31.85      ,
       28.8       , 23.        , 19.        , 14.        , 24.        ,
       21.        , 24.        , 21.6       , 24.        , 31.7       ,
       23.75      , 46.6       , 34.        , 15.5       , 28.8       ,
       13.5       , 13.        , 20.        , 20.        , 18.        ,
       14.25      , 29.        , 23.        , 22.        , 20.        ,
       24.        , 28.03333333, 29.9       , 30.5       , 17.5       ,
       38.        , 15.66666667, 12.        , 15.5       , 28.8       ,
       20.        , 18.5       , 30.5       , 29.        , 17.5       ])

In [ ]:
#check accuracy
from sklearn.metrics import r2_score
r2_B = r2_score(B_test, B_pred)
print(r2_B)

0.5234039877300759

In [ ]:
#by boosting using Gradient boosting
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
#build model
model_RG = GradientBoostingRegressor(n_estimators=100,random_state=42)
model_RG

GradientBoostingRegressor(random_state=42)

In [ ]:
#fit the model
model_RG.fit(A_train,B_train)

GradientBoostingRegressor(random_state=42)

In [ ]:
#predict the value
b_predRG = model_RG.predict(A_test)
b_predRG

array([31.75283743, 27.2042986 , 18.8013797 , 14.7466647 , 14.7466647 ,
       25.71344777, 24.97753626, 13.53760632, 20.32473057, 19.78180934,
       14.14924255, 36.59310446, 33.93268073, 14.7466647 , 25.946337  ,
       13.93545085, 25.88767336, 21.86603724, 13.93545085, 34.31843796,
       31.54223585, 20.10276147, 18.8013797 , 29.80458833, 16.07969489,
       25.69173538, 26.73305772, 26.27028461, 16.92118145, 14.10494709,
       24.26896898, 31.5114378 , 16.97622713, 24.25478223, 40.06406792,
       12.99996579, 22.21745879, 14.93904773, 14.7466647 , 29.80458833,
       23.18600665, 32.15229648, 23.05787904, 13.22437246, 23.32450619,
       24.87975825, 28.19228581, 23.31597735, 27.55906601, 29.76111082,
       25.52538999, 40.06406792, 31.22385256, 14.14924255, 22.92790835,
       13.93545085, 14.44112022, 25.00322799, 24.90681331, 19.65195584,
       14.00064707, 31.75283743, 25.92679367, 24.38766286, 20.10276147,
       24.25478223, 25.63244028, 32.87766715, 33.00893252, 16.07969489,
       35.26926942, 14.7466647 , 12.01926611, 17.69228565, 21.29108337,
       20.32473057, 17.69228565, 27.63636527, 32.64443635, 16.07969489])

In [ ]:
#check accuray
r2_bG = r2_score(B_test,b_predRG)
r2_bG

0.7143766553186786

In [ ]:
# heare the model accuracy is increase after using the Gradient bosting